version: '3'

services:
  ifcbdb:
    build: .
    container_name: ifcbdb
    volumes:
      - ./pyifcb:/pyifcb
      - ./ifcbdb:/ifcbdb
      - ifcbdb_static:/static
      - ./ifcb_data:/data
    networks:
      - nginx_network
      - postgres_network
      - memcached_network
      - redis_network
    depends_on:
      - postgres
      - memcached
      - redis

  celery:
    build: .
    container_name: celery
    command: celery -A ifcbdb worker -l info
    volumes:
      - ./pyifcb:/pyifcb
      - ./ifcbdb:/ifcbdb
      - ./ifcb_data:/data
    depends_on:
      - postgres
      - memcached
      - redis
    networks:
      - redis_network
      - postgres_network
      - memcached_network

  nginx:
    image: nginx:1.15
    container_name: nginx
    ports:
      - 9000:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ifcbdb_static:/static
    depends_on:
      - ifcbdb
    networks:
      - nginx_network

  postgres:
    image: mdillon/postgis:11-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=ifcb
      - POSTGRES_PASSWORD=ifcb
      - POSTGRES_DB=ifcb
    volumes:
      - ifcbdb_pg_data:/var/lib/postgresql/data
    networks:
      - postgres_network

  memcached:
    image: memcached:1.5.12-alpine
    container_name: memcached
    command: ["-m", "64m"]
    networks:
      - memcached_network

  redis:
    image: redis:5.0.4-alpine
    container_name: redis
    networks:
      - redis_network

networks:
  nginx_network:
    driver: bridge
  postgres_network:
    driver: bridge
  memcached_network:
    driver: bridge
  redis_network:
    driver: bridge

volumes:
  ifcbdb_static:
  ifcbdb_pg_data:
